### ISSUE TITLE
github_vars.yml?

### ISSUE THREAD

**Issue by luto** [EMnify/matrix-synapse-auto-deploy#2]
What is [`github_vars.yml`](https://github.com/EMnify/matrix-synapse-auto-deploy/blob/master/playbook.yml#L7) and where is it supposed to come from? It's not present on my system.

**Comment by mngiess** [comment]
github_vars.yml allows you to set your defaults for github access in the playbooks, you need to create and fill it yourself, e.g.

    ---
    name: 'Firstname Lastname'
    email: 'your email address'
    username: 'your github username'
    key_file: '~/.ssh/github_key.pem'  # Local path to your GitHub private key

**Comment by luto** [comment]
Thanks! Since I haven't seen this anywhere else and it doesn't seem to be documented in the readme so far, I'll prepare a PR later.
